runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: dindon-bath-team3:europe-west1:dindon-db
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: Qawwaqqaw97
  SQL_DATABASE: postgres
  INSTANCE_CONNECTION_NAME: dindon-bath-team3:europe-west1:dindon-db
